language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "N818+apYVl9c46M06Cgp3Pq3BN+Yv0LLCSLYSNIv/GAT0oGg42FWXXHGpkZOBUd52TjOs/WzS0M7k2zZ7TfU9Tq6NtD4ZHVPyaEPfKOAk/3EnOhgJSUAIHOV/vIMndikhmmmUloKXEWODTCv7lc+nSZLgT40S7n/RbMx7izAvy2JfywZXjusisAuwWzWLBtrdaV9N2QC6w440XLwNIu1WewRkbyj/Bkc5bSZJAmmaFKkwclfiy7j6h4PdlDZsNWLScOq8W6I9j0QyFN2zyWKyvoZhKf4MNQ/QAzSlUnXN4Nbeeq34i7iw/MHSra9S56/zmCKWkZMI8dd/l711CieogXSmTFRtRQjsGHK3fUqAFQtzk/+4qDn2O/jBjN0rObH7Lz503NoU/UMdCF0LBCkj9JqWNcblep8L5rXvCrR+NJklG3n0lEK236RO0uVKRnLsdSMBAZHg10SGkwIP1W82MctrbPEVNvwcXVSPsIP3QlGLkbgk5Hp+eAhx+9uPK+OzMomUX9LgD3PoBt56jwAYsBWOJfRQrB8DsHfncJgaEsX6xBR0ujt+zKUdd+qoemqGFnq6Mv+jakdvX/mn/z4+HA7oKV6iR0YkezAKN35k7oraWJKTu2zF76VNTIOsecum26rWh1Nyvq7nH5PDjAjBeGvveHhCVBx+hdTLbdcr6g="
